import { ReactNode } from 'react';
import './globals.css';
import { inter } from '@/utils/fonts';
import clsx from 'clsx';
import { Metadata } from 'next';
import LayoutContent from '@/components/layout-content';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="cs">
      <body
        className={clsx(
          inter.className,
          'flex min-h-screen flex-col bg-gradient-to-b from-blue-500 to-blue-900 text-white antialiased'
        )}
      >
        <LayoutContent>{children}</LayoutContent>
      </body>
    </html>
  );
}
